name: Go
on: [push]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.21.x]
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          make install

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5.1.0
        with:
          version: latest
          args: --verbose

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test
